### ISSUE TITLE
Not an issue, I'm asking for help.

### ISSUE THREAD

**Issue by Shaztech** [dsclee1/BRmesh-esp32-mqtt#3]
I don't have have HA, I'm using Blynk. Your code is a little advanced for me and I want to adapt it for my need.
I only have 2 lights (RGBW) that I use at the same time (always the same color, same state...). If I use your code unmodified I can see them and connect to them. But I cannot use them since I don't have HA.

I only want a simpler code, I can hardcode the lights unique ID, so no scan needed. And only commands for state, brightness and color (and true white mode). 

Can you help ?

Thanks

**Comment by Shaztech** [comment]
I've figured it out, removed HA and added Blynk.
Also if you don't want to re-register your lights each reboot, use a fixed "my_key". Choose a random one and stick with it. The lights will keep registered to this key, and you can only send packets with the same key.
I've removed the scan (add lights) on boot, and do it only with a button press.

**Comment by disruptivepatternmaterial** [comment]
hey can you share you code please? I am not following you here, but would love to emulate what you did...

**Comment by disruptivepatternmaterial** [comment]
yeah so just reusing the key is not sufficient, so I am wondering if you really got this working or it was an idea. So if you could clarify, please.

I say this because the esp32 holds a small list of the lights it has connected to, so while the lamp might be ok and not need changing or re-linking, the esp32 is no longer aware that is knows about the light, making it impossible for it to control, so I am back to the idea of having to persist the lamp list somewhere for the esp32 to reload on reboot

**Comment by Shaztech** [comment]
[BRmeshNode.zip](https://github.com/user-attachments/files/17203427/BRmeshNode.zip)

It working since May.
